version: "3.4"
services:
  auction-parser:
    image: docker.io/rfaita/exiva-parser:latest
    deploy:
      mode: replicated
      replicas: 5
    environment:
      - RABBITMQ_QUEUE=${RABBITMQ_QUEUE}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
      - MONGO_FULL_URL=${MONGO_FULL_URL}
    

  auction-parser-initial-page:
    image: docker.io/rfaita/exiva-parser-initial-page:latest
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - RABBITMQ_QUEUE=${RABBITMQ_QUEUE}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
      - MONGO_FULL_URL=${MONGO_FULL_URL}

  auction-notification:
    image: docker.io/rfaita/exiva-notification:latest
    deploy:
      mode: replicated
      replicas: 2
    environment:
      - RABBITMQ_QUEUE=${RABBITMQ_QUEUE}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
      - MONGO_FULL_URL=${MONGO_FULL_URL}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}