apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "exiva-parser-initial-page.fullname" . }}
  labels:
    {{- include "exiva-parser-initial-page.labels" . | nindent 4 }}
{{- with .Values.configmap }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}