apiVersion: v1
kind: Secret
metadata:
  name: {{ include "exiva-parser-initial-page.fullname" . }}
  labels:
    {{- include "exiva-parser-initial-page.labels" . | nindent 4 }}
type: Opaque
{{- with .Values.secrets }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
  
  