name: CD-notification

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:            

  deploy-notification:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: copy chart to k8s cluster
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.K8S_HOST }}
          username: ubuntu
          key: ${{ secrets.K8S_KEY }}
          source: "notification/chart/*"
          target: "/home/ubuntu/charts"
      - name: deploy to k8s cluster
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.K8S_HOST }}
          username: ubuntu
          key: ${{ secrets.K8S_KEY }}
          script: |
            cd /home/ubuntu/charts/notification/ && \
            export MONGO_FULL_URL=$(echo "${{ secrets.MONGO_FULL_URL }}" | base64) && \
            export RABBITMQ_PASS=$(echo "${{ secrets.RABBITMQ_PASS }}" | base64) && \
            sudo helm upgrade --install --wait --set secrets.MONGO_FULL_URL="$MONGO_FULL_URL",secrets.RABBITMQ_PASS=$RABBITMQ_PASS,configmap.GOOGLE_APPLICATION_CREDENTIALS='${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}' exiva-notification chart