# This is a basic workflow to help you get started with Actions

name: CD-parser

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:            

  deploy-parser-initial-page:
    runs-on: ubuntu-latest
    steps:
      - name: deploy to machine 1
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PARSER_HOST_1 }}
          username: ${{ secrets.PARSER_USER_1 }}
          password: ${{ secrets.PARSER_PASS_1 }}
          script: |
            docker login -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_API_KEY }} docker.io && \
            (docker stop tibia-auction-parser01 || true ) && \
            (docker rm -f tibia-auction-parser01 || true )  && \
            docker pull docker.io/rfaita/exiva-parser:latest && \
            docker run -d --restart unless-stopped \
            --network host \
            -e MONGO_FULL_URL="${{ secrets.MONGO_FULL_URL }}" \
            -e MONGO_HOST=${{ secrets.MONGO_HOST }} \
            -e MONGO_DB=${{ secrets.MONGO_DB }} \
            -e MONGO_USER=${{ secrets.MONGO_USER }} \
            -e MONGO_PASS="${{ secrets.MONGO_PASS }}" \
            -e RABBITMQ_HOST=${{ secrets.RABBITMQ_HOST }} \
            -e RABBITMQ_QUEUE=${{ secrets.RABBITMQ_QUEUE }} \
            -e RABBITMQ_USER=${{ secrets.RABBITMQ_USER }} \
            -e RABBITMQ_PASS="${{ secrets.RABBITMQ_PASS }}" \
            -e RABBITMQ_EXCHANGE=${{ secrets.RABBITMQ_EXCHANGE }} \
            --name tibia-auction-parser01 docker.io/rfaita/exiva-parser:latest
      - name: deploy to machine 2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PARSER_HOST_2 }}
          username: ${{ secrets.PARSER_USER_2 }}
          password: ${{ secrets.PARSER_PASS_2 }}
          script: |
            docker login -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_API_KEY }} docker.io && \
            (docker stop tibia-auction-parser01 || true ) && \
            (docker rm -f tibia-auction-parser01 || true )  && \
            docker pull docker.io/rfaita/exiva-parser:latest && \
            docker run -d --restart unless-stopped \
            --network host \
            -e MONGO_FULL_URL="${{ secrets.MONGO_FULL_URL }}" \
            -e MONGO_HOST=${{ secrets.MONGO_HOST }} \
            -e MONGO_DB=${{ secrets.MONGO_DB }} \
            -e MONGO_USER=${{ secrets.MONGO_USER }} \
            -e MONGO_PASS="${{ secrets.MONGO_PASS }}" \
            -e RABBITMQ_HOST=${{ secrets.RABBITMQ_HOST }} \
            -e RABBITMQ_QUEUE=${{ secrets.RABBITMQ_QUEUE }} \
            -e RABBITMQ_USER=${{ secrets.RABBITMQ_USER }} \
            -e RABBITMQ_PASS="${{ secrets.RABBITMQ_PASS }}" \
            -e RABBITMQ_EXCHANGE=${{ secrets.RABBITMQ_EXCHANGE }} \
            --name tibia-auction-parser01 docker.io/rfaita/exiva-parser:latest
      - name: deploy to machine 3
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PARSER_HOST_3 }}
          username: ${{ secrets.PARSER_USER_3 }}
          password: ${{ secrets.PARSER_PASS_3 }}
          script: |
            docker login -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_API_KEY }} docker.io && \
            (docker stop tibia-auction-parser01 || true ) && \
            (docker rm -f tibia-auction-parser01 || true )  && \
            docker pull docker.io/rfaita/exiva-parser:latest && \
            docker run -d --restart unless-stopped \
            --network host \
            -e MONGO_FULL_URL="${{ secrets.MONGO_FULL_URL }}" \
            -e MONGO_HOST=${{ secrets.MONGO_HOST }} \
            -e MONGO_DB=${{ secrets.MONGO_DB }} \
            -e MONGO_USER=${{ secrets.MONGO_USER }} \
            -e MONGO_PASS="${{ secrets.MONGO_PASS }}" \
            -e RABBITMQ_HOST=${{ secrets.RABBITMQ_HOST }} \
            -e RABBITMQ_QUEUE=${{ secrets.RABBITMQ_QUEUE }} \
            -e RABBITMQ_USER=${{ secrets.RABBITMQ_USER }} \
            -e RABBITMQ_PASS="${{ secrets.RABBITMQ_PASS }}" \
            -e RABBITMQ_EXCHANGE=${{ secrets.RABBITMQ_EXCHANGE }} \
            --name tibia-auction-parser01 docker.io/rfaita/exiva-parser:latest
      - name: deploy to machine 4
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PARSER_HOST_4 }}
          username: ${{ secrets.PARSER_USER_4 }}
          password: ${{ secrets.PARSER_PASS_4 }}
          script: |
            docker login -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_API_KEY }} docker.io && \
            (docker stop tibia-auction-parser01 || true ) && \
            (docker rm -f tibia-auction-parser01 || true )  && \
            docker pull docker.io/rfaita/exiva-parser:latest && \
            docker run -d --restart unless-stopped \
            --network host \
            -e MONGO_FULL_URL="${{ secrets.MONGO_FULL_URL }}" \
            -e MONGO_HOST=${{ secrets.MONGO_HOST }} \
            -e MONGO_DB=${{ secrets.MONGO_DB }} \
            -e MONGO_USER=${{ secrets.MONGO_USER }} \
            -e MONGO_PASS="${{ secrets.MONGO_PASS }}" \
            -e RABBITMQ_HOST=${{ secrets.RABBITMQ_HOST }} \
            -e RABBITMQ_QUEUE=${{ secrets.RABBITMQ_QUEUE }} \
            -e RABBITMQ_USER=${{ secrets.RABBITMQ_USER }} \
            -e RABBITMQ_PASS="${{ secrets.RABBITMQ_PASS }}" \
            -e RABBITMQ_EXCHANGE=${{ secrets.RABBITMQ_EXCHANGE }} \
            --name tibia-auction-parser01 docker.io/rfaita/exiva-parser:latest
      - name: deploy to machine 5
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PARSER_HOST_5 }}
          username: ${{ secrets.PARSER_USER_5 }}
          password: ${{ secrets.PARSER_PASS_5 }}
          script: |
            docker login -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_API_KEY }} docker.io && \
            (docker stop tibia-auction-parser01 || true ) && \
            (docker rm -f tibia-auction-parser01 || true )  && \
            docker pull docker.io/rfaita/exiva-parser:latest && \
            docker run -d --restart unless-stopped \
            --network host \
            -e MONGO_FULL_URL="${{ secrets.MONGO_FULL_URL }}" \
            -e MONGO_HOST=${{ secrets.MONGO_HOST }} \
            -e MONGO_DB=${{ secrets.MONGO_DB }} \
            -e MONGO_USER=${{ secrets.MONGO_USER }} \
            -e MONGO_PASS="${{ secrets.MONGO_PASS }}" \
            -e RABBITMQ_HOST=${{ secrets.RABBITMQ_HOST }} \
            -e RABBITMQ_QUEUE=${{ secrets.RABBITMQ_QUEUE }} \
            -e RABBITMQ_USER=${{ secrets.RABBITMQ_USER }} \
            -e RABBITMQ_PASS="${{ secrets.RABBITMQ_PASS }}" \
            -e RABBITMQ_EXCHANGE=${{ secrets.RABBITMQ_EXCHANGE }} \
            --name tibia-auction-parser01 docker.io/rfaita/exiva-parser:latest
      